spring.application.name=Crud
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/jobboard
spring.datasource.username=maissa
spring.datasource.password=maissa962001
spring.datasource.driver-class-name =com.mysql.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
